### ISSUE TITLE
Pendientes cambios en report

### ISSUE THREAD

**Issue by cgosorio** [Jazriel/WhatAClass#41]
¿recibiste mi email con el pdf anotado con mis comentarios a la memoria?

En la actualización de hace 4 horas, todavía no hay ningún cambio incorporado.

**Comment by cgosorio** [comment]
OK, veo que algunos comentarios están incorporados, pero que muchos están pendientes, así que me imagino que justo hoy estarás en ello

**Comment by Jazriel** [comment]
La mayoría de los cambios no tienen descripción y me preguntaba si era por alguna razón en específico o si se basan en una leyenda que no conozco.

**Comment by Jazriel** [comment]
También puede ser que no funcione bien okular ya que creo que el último sí que tiene descripción pero creo que es el único.

**Comment by cgosorio** [comment]
los subrayados en amarillo son sólo para marcar palabras en inglés que en algún comentario previo sugería poner en cursiva con el comando \emph, creo que te refieres a eso



-- 
Dr. César García-Osorio
Dpto. de Ingeniería Civil , Área de Lenguajes y Sistemas Informáticos
Universidad de Burgos, Avda. Cantabría, s/n, 09006 Burgos (Spain)
Tel:     +34 947 25 9358,   Fax:     +34 947 25 8910
e-mail: cgosorio@ubu.es <mailto:cgosorio@ubu.es>, webpage: http://cgosorio.es <http://cgosorio.es/>, http://admirable-ubu.es

**Comment by cgosorio** [comment]
Sólo para estar seguros, en la página de portada sugiero dos cambios, añadir el paquete fontenc y modificar la parte de la plantilla correspondiente a los tutores, ¿esos comentarios se ven en okular?

**Comment by Jazriel** [comment]
No, se ven como si hubieras tachado informática en la frase 'TFG del Grado en Ingenierı́a Informática' y toda la frase 'Tutor: Dr. José Francisco Dı́ez Pastor y Dr. César
Ignacio Garcı́a Osorio'

**Comment by Jazriel** [comment]
Si me dices que lector usas para usarle en vez de hacerte editar el archivo.

**Comment by cgosorio** [comment]
Pues un problema del visor, esos tachados llevan asociado un comentario que sugieren las modificaciones.

-- 
Dr. César García-Osorio
Dpto. de Ingeniería Civil , Área de Lenguajes y Sistemas Informáticos
Universidad de Burgos, Avda. Cantabría, s/n, 09006 Burgos (Spain)
Tel:     +34 947 25 9358,   Fax:     +34 947 25 8910
e-mail: cgosorio@ubu.es <mailto:cgosorio@ubu.es>, webpage: http://cgosorio.es <http://cgosorio.es/>, http://admirable-ubu.es

**Comment by cgosorio** [comment]
Yo uso el Adobe Acrobat para las ediciones, pero para poder ver los comentarios con el Adobe Reader es suficiente. La última vez que lo instalé en linux, seguí las siguientes instrucciones.


sudo apt-get install libstdc++6:i386
## Checking/Installing GDebi Package Installer
#which gdebi
## If Not there then:
#sudo apt-get install gdebi
cd Descargas
wget ftp://ftp.adobe.com/pub/adobe/reader/unix/9.x/9.5.5/enu/AdbeRdr9.5.5-1_i386linux_enu.deb
sudo su -c "gdebi ./AdbeRdr*.deb"


See also: http://askubuntu.com/questions/89127/how-do-i-install-adobe-acrobat-reader-deb-package-downloaded-from-adobe-website/89188#89188 <http://askubuntu.com/questions/89127/how-do-i-install-adobe-acrobat-reader-deb-package-downloaded-from-adobe-website/89188#89188>
Siguiendo las instrucciones de: http://askubuntu.com/questions/767937/how-to-install-adobe-acrobat-in-ubuntu-16-04 <http://askubuntu.com/questions/767937/how-to-install-adobe-acrobat-in-ubuntu-16-04>
I followed the tips above on Kubuntu 16.04 64 bit:

sudo add-apt-repository "deb http://archive.canonical.com/ precise partner" sudo apt-get update sudo apt install adobereader-enu

After properly installed Adobe Reader, don’t forget to remove the Canonical Partners repository for Precise:

sudo add-apt-repository -r "deb http://archive.canonical.com/ precise partner"




-- 
Dr. César García-Osorio
Dpto. de Ingeniería Civil , Área de Lenguajes y Sistemas Informáticos
Universidad de Burgos, Avda. Cantabría, s/n, 09006 Burgos (Spain)
Tel:     +34 947 25 9358,   Fax:     +34 947 25 8910
e-mail: cgosorio@ubu.es <mailto:cgosorio@ubu.es>, webpage: http://cgosorio.es <http://cgosorio.es/>, http://admirable-ubu.es

**Comment by Jazriel** [comment]
He estado trasteando y he instalado Foxit Reader que deja leer las anotaciones

**Comment by cgosorio** [comment]
Estupendo! Yo el Foxit reader no lo he usado nunca, pero he oído hablar bien de él. Una de las ventajas del Adobe Reader es que tiene un panel en el que se muestra el listado de comentarios, aunque supongo que Foxit reader tendrá algo parecido. Así no se te pasa ninguno. Algunos de mis sugerencias son sólo para poner comas aquí y allá. Si el Foxit tiene el panel de comentarios, mejor que el visor del documento, sería usar ese panel, así evitas que se te pase algún comentario.


-- 
Dr. César García-Osorio
Dpto. de Ingeniería Civil , Área de Lenguajes y Sistemas Informáticos
Universidad de Burgos, Avda. Cantabría, s/n, 09006 Burgos (Spain)
Tel:     +34 947 25 9358,   Fax:     +34 947 25 8910
e-mail: cgosorio@ubu.es <mailto:cgosorio@ubu.es>, webpage: http://cgosorio.es <http://cgosorio.es/>, http://admirable-ubu.es

**Comment by cgosorio** [comment]
Supongo que ya lo habrás descubierto, pero por si acaso. En el Foxit Reader, la característica que te comentaba del Adobe Reader se encuentra en View | Navigation Panels | Comments

**Comment by cgosorio** [comment]
¿Como van los cambios? En cuanto los tengas haz el push al servidor y me avisas para darle un vistazo , todavía había secciones importantes que faltaban. 

Otra cosa, el utilizar tu validación con Seshat, ¿cómo va?
